version: 2

models:
  - name: customer_purchase
    description: "Total purchase by each customer"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: cumulative_sales
    description: "Cumulative sales datewise"
    columns:
      - name: o_orderdate
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: date_dim
    description: "This is date dim with incremental load"
    columns:
      - name: D_DATE
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: incremental_time
    description: "This is time dim with incremental load"
    columns:
      - name: t_time
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: dept
    description: "This is department table"
    columns:
      - name: deptno
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
          - accepted_values:
              values: [10, 20, 30, 40]
  - name: emp
    description: "This is employee table"
    columns:
      - name: empno
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: deptno
        description: "The foreign key for this table"
        data_tests:
          - relationships:
              to: ref('dept')
              field: deptno
